backend:
  name: github
  repo: 2005Gokulakrishnan/weding-decore-website
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: homepage
    label: Homepage
    files:
      - label: Hero Section
        name: hero
        file: content/homepage.json
        fields:
          - label: Hero Title
            name: hero_title
            widget: string

          - label: Hero Description
            name: hero_description
            widget: text

          - label: Hero Button Text
            name: hero_button_text
            widget: string
